#include-once

Global Const $CRED_TYPE_GENERIC = 1
Global Const $CRED_TYPE_DOMAIN_PASSWORD = 2
Global Const $CRED_TYPE_DOMAIN_CERTIFICATE = 3
Global Const $CRED_TYPE_DOMAIN_VISIBLE_PASSWORD = 4
Global Const $CRED_TYPE_GENERIC_CERTIFICATE = 5
Global Const $CRED_TYPE_DOMAIN_EXTENDED = 6
Global Const $CRED_TYPE_MAXIMUM = 7
Global Const $CRED_TYPE_MAXIMUM_EX = $CRED_TYPE_MAXIMUM + 1000
